#!/usr/bin/env bash

set -e
script_dir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P)"

sudo_opts=()
if [ ! -z "${SSH_TTY}" ]; then
  export SUDO_ASKPASS="${script_dir}/sudo/sudo-op-askpass"
  sudo_opts=('--askpass')
fi

if [ -r /etc/os-release ]; then
  source /etc/os-release
  case "${ID}" in
    'fedora' )
      sudo "${sudo_opts[@]}" true &>/dev/null
      xargs sudo "${sudo_opts[@]}" dnf install -y < "${script_dir}/packages/${ID}-${VARIANT_ID/cloud/server}.txt"
      ;;

    'ubuntu' )
      sudo "${sudo_opts[@]}" true &>/dev/null
      xargs sudo "${sudo_opts[@]}" apt-get install -y < "${script_dir}/packages/${ID}.txt"
      mkdir -p "${HOME}/.local/bin"
      command -v batcat &>/dev/null && ln -snf "$(which batcat)" "${HOME}/.local/bin/bat"
      command -v fdfind &>/dev/null && ln -snf "$(which fdfind)" "${HOME}/.local/bin/fd"
      ;;

    * )
      >&2 echo "Unknown distro '${ID}'. Skipping package install."
      ;;
  esac
fi

# Install software
"${script_dir}/install" <<<'B'
