#!/bin/sh

set -e
ctags=${CTAGS_PATH:-$(which ctags)}
dir="$(git rev-parse --show-toplevel)"
trap 'rm -f "${dir}/$$.tags"' EXIT
git ls-files | \
  ${ctags} -L - -f"${dir}/$$.tags"
mv "${dir}/$$.tags" "${dir}/tags"
